export const SET_CSRFTOKEN = "SET_CSRFTOKEN"
export const LOADING_START = 'LOADING_START'
export const LOADING_FINISH = 'LOADING_FINISH'
// export const TASKS_REQUEST_TASKS = 'TASKS_REQUEST_TASKS'
export const TASKS_RECEIVE_TASKS = 'TASKS_RECEIVE_TASKS'
// export const TASK_APPLICATIONS_REQUEST_TASK_APPLICATIONS = 'TASK_APPLICATIONS_REQUEST_TASK_APPLICATIONS'
export const TASK_APPLICATIONS_RECEIVE_TASK_APPLICATIONS = 'TASK_APPLICATIONS_RECEIVE_TASK_APPLICATIONS'
