export const SET_CSRFTOKEN = "SET_CSRFTOKEN"
export const LOADING_START = 'LOADING_START'
export const LOADING_FINISH = 'LOADING_FINISH'
export const TASKS_RECEIVE_TASKS = 'TASKS_RECEIVE_TASKS'
export const TASK_APPLICATIONS_RECEIVE_TASK_APPLICATIONS = 'TASK_APPLICATIONS_RECEIVE_TASK_APPLICATIONS'
export const TASK_APPLICATIONS_ADD_TASK_APPLICATION = 'TASK_APPLICATIONS_ADD_TASK_APPLICATION'
export const MESSAGE_INBOX_RECEIVE_MESSAGE = 'MESSAGE_INBOX_RECEIVE_MESSAGE'
export const MESSAGE_OUTBOX_RECEIVE_MESSAGE = 'MESSAGE_OUTBOX_RECEIVE_MESSAGE'
